config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions'
  }

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  devise_scope :user do
    get  '/redirect_to_keycloak', to: 'sessions#redirect_to_keycloak'
    get  '/authenticate_by_keycloak', to: 'sessions#authenticate_by_keycloak'
  end

  root to: 'orders#index'

  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to:          'orders#search_by',
      as:          :search_order_by,
      constraints: {field: /code|ext_code/}

  get '/orders/order_type_attributes/:id' => 'orders#get_order_type_attributes'

  get '/orders/list', to: 'orders#list'

  get '/tasks', to: 'tasks#index'

  resources :orders, only: [:show, :edit, :update, :index, :new, :create]

  resources :profiles, only: [:create, :update]

  namespace :imprint do
    resources :prints, only: [] do
      get :print, on: :collection
      post :print_task, on: :collection
    end
  end

  namespace :admin do
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss, on: :member
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module:      :v1,
          constraints: APIConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: {id: /.*/}
      resources :orders, only: actions
      resources :profiles, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/controllers/admin/order_types_controller.rb
class Admin::OrderTypesController < ApplicationController
  before_action :authenticate_user!
  self.hbw_available = true

  before_action :require_order_type, only: [:show, :activate, :dismiss, :destroy]
  before_action :admin_only

  def index
    @order_types = OrderType.active
  end

  def show; end

  def create
    file_content = params.require(:order_type).permit(:file)[:file].read
    @order_type = OrderType.new(file: file_content)

    if @order_type.valid?
      render_valid
    else
      render_invalid
    end
  end

  def destroy
    @order_type.make_invisile
    flash[:success] = t('.destroyed')

    redirect_to admin_order_types_path
  end

  def activate
    @order_type.activate

    flash[:success] = t('.activated')
    redirect_to action: 'index'
  end

  def dismiss
    @order_type.destroy

    flash[:success] = t('.dismissed')
    redirect_to action: 'index'
  end

  def lookup
    render json: OrderType.lookup(params.require(:q)).to_json
  end

  private

  def require_order_type
    @order_type = OrderType.find(params.require(:id))
  end

  def render_valid
    if @order_type.save_if_differs!
      flash[:success] = t('.uploaded')
      render action: 'show'
    else
      flash[:error] = '%s: %s' % [t('.equal_exists'), @order_type.code]
      redirect_to action: 'index'
    end
  end

  def render_invalid
    flash[:error] = @order_type.errors.full_messages.join(', ')
    redirect_to action: 'index'
  end
end

app/views/admin/order_types/_activate_dismiss.html.haml
= link_to t('activate'), activate_admin_order_type_path(@order_type), method: :put, class: ' btn btn-danger'

= link_to t('dismiss'), dismiss_admin_order_type_path(@order_type), method: :delete, class: 'btn btn-primary'

app/views/admin/order_types/_upload.html.haml
= form_for :order_type do |f|
  = f.file_field :file, :type => 'file', 'data-show-preview'=> 'false', :class => 'file'
                                     

app/views/admin/order_types/index.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')

.row
  .col-xs-12.col-sm-12.col-md-6.col-lg-6
    %table.table.table-hover.table-striped
      %thead
        %th= OrderType.human_attribute_name(:name)
        %th(colspan="2")= OrderType.human_attribute_name(:code)
      %tbody
        - @order_types.each do |order_type|
          %tr
            %td.order-name
              %a{ href: admin_order_type_path(order_type) }= order_type.name
            %td= order_type.code
            %td
              = link_to(admin_order_type_path(order_type),
                        method: :delete,
                        class: 'text-danger',
                        data: { confirm: t('.confirmation', order_type: order_type.name), confirm_title: t('.order_type_removal'), confirm_proceed: t('.yes_remove') }) do
                %i.fas.fa-trash-alt
  .col-xs-12.col-sm-12.col-md-6.col-lg-6
    %h5= t('.add')
    = render partial: 'upload'

app/views/admin/order_types/show.html.haml
- content_for(:title, @order_type.name)

%h2= @order_type.name
.row
  .col-xs-12.col-sm-12.col-md-8.col-lg-9
    = preserve(@order_type.html_from_file.html_safe)
  .col-xs-12.col-sm-12.col-md-4.col-lg-3
    - if @order_type.active
      %div= t('.activated')
      = link_to admin_order_types_path do
        %i.fas.fa-long-arrow-alt-left><
        = t('.back')
    - else
      %div= t('.activate_dismiss')
      = render partial: 'activate_dismiss'