config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions'
  }

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  devise_scope :user do
    get  '/redirect_to_keycloak', to: 'sessions#redirect_to_keycloak'
    get  '/authenticate_by_keycloak', to: 'sessions#authenticate_by_keycloak'
  end

  root to: 'orders#index'

  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to:          'orders#search_by',
      as:          :search_order_by,
      constraints: {field: /code|ext_code/}

  get '/orders/order_type_attributes/:id' => 'orders#get_order_type_attributes'

  get '/orders/list', to: 'orders#list'

  get '/tasks', to: 'tasks#index'

  resources :orders, only: [:show, :edit, :update, :index, :new, :create]

  resources :profiles, only: [:create, :update]

  namespace :imprint do
    resources :prints, only: [] do
      get :print, on: :collection
      post :print_task, on: :collection
    end
  end

  namespace :admin do
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss, on: :member
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module:      :v1,
          constraints: APIConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: {id: /.*/}
      resources :orders, only: actions
      resources :profiles, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/models/user.rb
class User < ActiveRecord::Base
  class << self
    def id_from_email(email)
      select(:id).find_by(email:).try(:id)
    end

    def lookup(query, limit = 10)
      s = query.mb_chars.downcase.to_s

      where(<<-SQL, *(["%#{s}%"] * 3))
        lower(name) like ?
          OR lower(last_name) like ?
          OR lower(middle_name) like ?
      SQL
        .select('id, name, middle_name, last_name')
        .order_by_name
        .limit(limit)
        .map { |u| {id: u.id, text: u.full_name} }
    end

    def order_by_name
      order(:name, :id)
    end

    def empty
      @empty ||= Empty.new
    end

    def from_keycloak(user_data)
      user = find_or_create_user_from_keycloak(user_data)
      user.update_attribute(:role, user_data[:role])

      user
    end

    private

    def find_or_create_user_from_keycloak(user_data)
      where(email: user_data[:email]).first_or_create do |new_user|
        new_user.email = user_data[:email]
        new_user.name = user_data[:given_name]
        new_user.last_name = user_data[:family_name] || '-'
        new_user.company = user_data[:company] || '-'
        new_user.department = user_data[:department] || '-'
        new_user.password = Devise.friendly_token
        new_user.directory = 'hydra_sso'
        new_user.role = user_data[:role]
      end
    end
  end

  include HasRole
  include HasAPIToken

  default_scope { order(last_name: :asc, name: :asc, middle_name: :asc) }

  def full_name
    [name, last_name].join ' '
  end

  def from_sso?
    directory == 'hydra_sso'
  end

  devise :database_authenticatable, :rememberable, :trackable, :validatable, :encryptable

  validates :name,        presence: true
  validates :last_name,   presence: true
  validates :company,     presence: true
  validates :department,  presence: true
  validates :directory,   inclusion: {
    in:      %w(hydra_sso internal),
    message: "%{value} must be 'hydra_sso' or 'internal'"
  }

  has_many :profiles, dependent: :destroy
  has_many :orders,   dependent: :restrict_with_exception
end

app/controllers/api/v1/users_controller.rb
module API
  module V1
    class UsersController < API::BaseController
      include HttpAuthentication if !Rails.env.development? || ENV['HOMS_API_USE_AUTH']

      PARAMS_ATTRIBUTES = [:name, :last_name, :middle_name, :company,
                           :department, :email, :role, :password, :external,
                           :blocked, :password_salt, :encrypted_password].freeze

      private

      def user_params
        params.require(:user).permit(*PARAMS_ATTRIBUTES).tap do |hash|
          hash[:password_confirmation] = hash[:password] if
            hash[:password]
        end
      end

      def resource_set(resource = nil)
        resource ||= resource_class.find_by_email!(params[:id])
        super
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  self.hbw_available = true

  PARAMS_ATTRIBUTES = [:name, :last_name, :middle_name, :company, :department,
                       :email, :role, :password, :password_confirmation].freeze

  before_action :authenticate_user!
  before_action :admin_only, except: [:show, :lookup]
  before_action :find_user, except: [:new, :add, :index, :lookup]

  def index
    @users = User.all
  end

  def show
    unless @user == current_user || current_user.admin?
      flash[:alert] = t('access_denied')
      redirect_back(fallback_location: '/')
    end
  end

  def update
    attributes = secure_params
    if attributes[:password].blank?
      attributes.delete(:password)
      attributes.delete(:password_confirmation)
    end
    if @user.update(attributes)
      redirect_to users_path, notice: t('user_updated')
    else
      render action: :edit
    end
  end

  def destroy
    @user.destroy

    redirect_to users_path, notice: t('user_deleted')
  rescue ActiveRecord::DeleteRestrictionError
    flash[:alert] = t('users.destroy.user_has_orders', user_name: @user.name)

    redirect_to user_path, id: @user.id
  end

  def edit; end

  def new
    @user = User.new
  end

  def add
    @user = User.new(secure_params)

    if @user.save
      flash[:success] = t('.added')
      redirect_to users_path
    else
      render action: :new
    end
  end

  def generate_api_token
    @user.generate_api_token
    render action: 'show'
  end

  def clear_api_token
    @user.clear_api_token
    render action: 'show'
  end

  def lookup
    render json: User.lookup(params.require(:q)).to_json
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def secure_params
    params.require(:user).permit(*PARAMS_ATTRIBUTES)
  end
end

app/views/users/_form_fields.html.haml
= render partial: 'layouts/form_errors', locals: { record: @user }
= f.input :name, autofocus: true, required: false, disabled: from_sso
= f.input :middle_name, required: false
= f.input :last_name, required: false, disabled: from_sso
= f.input :email, required: false, disabled: from_sso
- if @user == @current_user
  = f.input :role, disabled: from_sso do
    %span.form-control
      = roles_for_select.find { |(_, role)| role == @user.role }.first
- else
  = f.input :role, as: :select, collection: roles_for_select, disabled: from_sso
= f.input :company, required: false, disabled: from_sso
= f.input :department, required: false, disabled: from_sso
- unless from_sso
  = f.input :password
  = f.input :password_confirmation

app/views/users/_user.html.haml
%tr
  %td
    %a{ href: user_path(user) }= user.full_name
  %td= user.email
  %td= t user.role_i18n_key
  %td= user.department
  %td= user.company
  %td= boolean_indicator(user.api_token?)

app/views/users/edit.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')
= simple_form_for(@user,
                  method: 'put',
                  wrapper: :horizontal_form,
                  html: { class: 'form-horizontal order-edit-form col-sm-6' }) do |f|
  = render partial: 'form_fields', locals: { f: f, 
                                             from_sso: @user.from_sso? }
  = f.submit t('save'), class: 'btn btn-primary pull-right'

app/views/users/index.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')

.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th= User.human_attribute_name(:full_name)
        %th= User.human_attribute_name(:email)
        %th= User.human_attribute_name(:role)
        %th= User.human_attribute_name(:department)
        %th= User.human_attribute_name(:company)
        %th= User.human_attribute_name(:api_token)
    %tbody
      - @users.each do |user|
        = render user
= link_to t('add'), new_user_path, class: 'btn btn-primary'

app/views/users/new.html.haml
- content_for(:title, t('.title'))
.authform
  = simple_form_for @user || :user, url: add_users_path, html: { role: 'form'} do |f|
    %h3= t('.title')
    = render partial: 'form_fields', locals: { f: f, 
                                               from_sso: @user.from_sso? }
    = f.submit t('add'), class: 'btn btn-primary pull-right'

app/views/users/show.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')
.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    %p= "%s: %s"%[User.human_attribute_name(:full_name), @user.full_name]
    %p= "%s: %s"%[User.human_attribute_name(:email), @user.email]
    %p= "%s: %s"%[User.human_attribute_name(:role), t(@user.role_i18n_key)]
    %p= "%s: %s"%[User.human_attribute_name(:company), @user.company]
    %p= "%s: %s"%[User.human_attribute_name(:department), @user.department]
    %p= "%s: %s"%[User.human_attribute_name(:api_token), @user.api_token]
    .row
      .col-xs-12
        = link_to t('edit'), edit_user_path, class: 'btn btn-primary'
        - if @user.api_token?
          = link_to t('.renew_api_token'), generate_api_token_user_path(@user), method: 'put', class: 'btn btn-danger', data: { confirm: t('.renew_api_token_warning'), confirm_proceed: t('.yes_renew') }
          = link_to t('.clear_api_token'), clear_api_token_user_path(@user), method: 'delete', class: 'btn btn-danger', data: { confirm: t('.clear_api_token_warning'), confirm_proceed: t('.yes_clear') }
        - else
          = link_to t('.generate_api_token'), generate_api_token_user_path(@user), method: 'put', class: 'btn btn-primary'
%br
.row
  .col-xs-12
    = link_to t('.delete_user'), user_path, method: 'delete', class: 'btn btn-danger'