config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions'
  }

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  devise_scope :user do
    get  '/redirect_to_keycloak', to: 'sessions#redirect_to_keycloak'
    get  '/authenticate_by_keycloak', to: 'sessions#authenticate_by_keycloak'
  end

  root to: 'orders#index'

  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to:          'orders#search_by',
      as:          :search_order_by,
      constraints: {field: /code|ext_code/}

  get '/orders/order_type_attributes/:id' => 'orders#get_order_type_attributes'

  get '/orders/list', to: 'orders#list'

  get '/tasks', to: 'tasks#index'

  resources :orders, only: [:show, :edit, :update, :index, :new, :create]

  resources :profiles, only: [:create, :update]

  namespace :imprint do
    resources :prints, only: [] do
      get :print, on: :collection
      post :print_task, on: :collection
    end
  end

  namespace :admin do
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss, on: :member
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module:      :v1,
          constraints: APIConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: {id: /.*/}
      resources :orders, only: actions
      resources :profiles, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/models/order.rb
class Order < ActiveRecord::Base
  class << self
    def id_from_code(code)
      select(:id, :order_type_id).find_by(code:).try(:id)
    end
  end

  include HasSequencedColumn

  has_sequenced_column :code

  belongs_to :order_type
  belongs_to :user

  validates :order_type, presence: true
  validates_with OrderDataValidator
  after_validation :coerce_values, if: ->(rec) { rec.errors.empty? }

  delegate :fields, :field_definition_set, to: :order_type
  delegate :name, :code, :print_form_code, to: :order_type, prefix: true

  default_scope { includes(:order_type).order('created_at DESC') }
  scope :data_fields, ->(data) { where('data @> ?', data.to_json) }
  scope :data_datetime_range, lambda { |field, from, to|
    where('(data->>:field)::timestamp between coalesce(:from, (data->>:field)::timestamp) and coalesce(:to, (data->>:field)::timestamp)',
          {field:, from:, to:})
  }

  enum state: %i(to_execute in_progress done)

  def user_full_name
    user ? user.full_name : ''
  end

  def self.state_i18n_key(state)
    "orders.states.#{state}"
  end

  def field_def_hash(name)
    order_type.fields[name.intern]
  end

  def order_type_id=(*)
    super.tap { initialize_fields }
  end

  def initialize_fields
    self[:data] = field_definition_set.nil_fields_values
  end

  def data=(hash)
    initialize_fields if data.nil?
    self[:data] = data.merge(hash)
  end

  private

  def coerce_values
    self[:data] = field_definition_set.coerce(data)
  end
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  class << self
    def lookup(query)
      s = query.mb_chars.downcase.to_s

      active.where('lower(name) like ?', "%#{s}%")
            .select('id, name')
            .order(name: :asc)
            .map { |e| {id: e.id, text: e.name} }
    end

    def id_from_code(code)
      active.select(:id).find_by(code:).try(:id)
    end
  end

  include FileContainsYaml

  validates_with OrderTypeFileValidator

  has_many :orders
  before_destroy :check_for_orders

  serialize :fields

  scope :active, -> { where(active: true).order(name: :asc) }
  scope :code, ->(code) { where(active: true, code:) }

  def initialize(*)
    super

    parse_file
  end

  def save_if_differs!
    last_one = self.class.code(code).last
    return false if self == last_one

    save!
  end

  def ==(other)
    other && other.code == code && other.fields == fields
  end

  def activate
    last_one = self.class.code(code).last
    transaction do
      last_one&.update_column(:active, false)
      update_column(:active, true)
    end
  end

  def nil_fields_values
    field_definition_set.nil_fields_values
  end

  def field_definition_set
    CustomFields::FieldDefSet.new(fields)
  end

  def filter_field_definition_set
    filter_fields = fields.each_with_object({}) do |(key, value), h|
      value[:type] = 'datetime_range' if value[:type] == 'datetime'

      h[key] = value
    end

    CustomFields::FieldDefSet.new(filter_fields)
  end

  def make_invisile
    update_attribute(:active, false)
  end

  private

  def parse_file
    OrderTypeFileValidator.new.validate self
    return unless errors.empty?

    self.fields          = hash_from_file[:order_type][:fields]
    self.code            = hash_from_file[:order_type][:code]
    self.name            = hash_from_file[:order_type][:name]
    self.print_form_code = hash_from_file[:order_type][:print_form_code]
  end

  def check_for_orders
    if orders.any?
      errors.add(:base, :cannot_delete_as_orders_exist)
      false
    else
      true
    end
  end
end

app/controllers/api/v1/orders_controller.rb
module API
  module V1
    class OrdersController < API::BaseController
      include HttpAuthentication if !Rails.env.development? || ENV['HOMS_API_USE_AUTH']

      PARAMS_ATTRIBUTES = [:order_type_code, :user_email, :ext_code, :bp_id,
                           :bp_state, :state, :done_at, :archived, :estimated_exec_date].freeze

      private

      def resource_set(resource = nil)
        resource ||= Order.find_by_code(params[:id])
        instance_variable_set("@#{resource_name}", resource)
      end

      def order_params
        params.require(:order).permit(*PARAMS_ATTRIBUTES, data: {}).tap do |params|
          replace_user_email! params if params[:user_email]
          replace_order_type_code! params if params[:order_type_code]
        end
      end

      def replace_user_email!(params)
        user_id = User.id_from_email params[:user_email]
        replace!(params, :user_email, :user_id, user_id)
      end

      def replace_order_type_code!(params)
        order_type_id = OrderType.id_from_code params[:order_type_code]
        raise ActiveRecord::RecordNotFound unless order_type_id

        replace!(params, :order_type_code, :order_type_id, order_type_id)
      end

      def replace!(params, code_key, id_key, id_val)
        record_not_found unless id_val

        params.delete code_key
        params[id_key] = id_val
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < API::BaseController
  extend Imprint::Mixin

  inject['services.order_printing_service']

  before_action :authenticate_user!
  self.hbw_available = true

  respond_to :html

  before_action :set_order, only: [:new, :create]

  def show; end

  # GET /orders/search_by/{:code | :ext_code}/
  def search_by
    @criteria = "#{Order.human_attribute_name(params[:field])}: " \
                "'#{params[:value]}'"
    resource_set Order.find_by!(params[:field] => params[:value])
    render action: :show
  end

  def index
    orders = list_filter.list_orders

    render 'orders/index', locals: {orders: orders.page(page_params[:page]).per(page_params[:page_size]), total_items: orders.size}
  end

  def list
    render 'orders/list', locals: {orders: list_filter.list_orders.page(page_params[:page]).per(page_params[:page_size])}
  end

  def edit; end

  def new
    if request.xml_http_request?
      @order.order_type_id = params[:order_type_id]
      render partial: params[:partial_name]
    else
      @order.order_type_id = OrderType.active.first.id
    end
  end

  def create
    init_order!

    if @order.save
      redirect_to order_url(@order.code)
    else
      render 'new'
    end
  end

  def update
    @order.data = params[:order][:data]
    @order.update(order_common_params)

    if @order.save
      redirect_to order_url(@order.code)
    else
      render 'edit'
    end
  end

  def set_order
    @order = Order.new
  end

  def get_order_type_attributes
    order_type = OrderType.find(params[:id])

    render json: {options: order_type.fields}
  end

  protected

  def resource_get
    instance_variable_get("@#{resource_name}")
  end

  def list_filter
    @list_filter ||= order_printing_service.build_filter(current_user, params)
  end
  helper_method :list_filter

  def record_not_found
    flash[:error] = if @criteria.nil?
                      t('record_not_found')
                    else
                      t('orders.search_by_not_found', criteria: @criteria)
                    end

    redirect_to orders_path
  end

  def resource_set(resource = nil)
    resource ||= Order.find_by!(code: params[:id])
    instance_variable_set("@#{resource_name}", resource)
  end

  private

  def order_common_params
    params.require(:order).permit(:estimated_exec_date)
  end

  def sort_params
    params.permit(:sort_by, :order)
  end

  def init_order!
    @order.order_type_id = params[:order_type_id] || OrderType.active.first.id
    @order.data = params[:order][:data]
    @order.user_id = current_user.id
    @order.update(order_common_params)
  end
end

app/helpers/orders_helper.rb
FILE_LIST_SCHEMA = Dry::Schema.Params do
  required(:file_list).array(:hash) do
    required(:url).filled
    required(:name).filled
    required(:origin_name).filled
    required(:real_name).filled
    required(:field_name).filled
    required(:upload_time).filled
    required(:end_point).filled
    required(:bucket).filled
  end
end

module OrdersHelper
  EMPTY_VALUE = '—'.freeze

  def prettify_value(value, field = {})
    if value.is_a?(Array)
      return value.map { |v| prettify_value(v, field) }.join(', ')
    end

    prettify_by_type(value, field)
  end

  def prettify_by_type(value, field)
    case field[:type]
    when 'datetime'
      prettify_date(value)
    when 'boolean'
      prettify_boolean(value)
    when 'json'
      prettify_json(value)
    else value.to_s.presence || EMPTY_VALUE
    end
  end

  def prettify_date(value)
    if value.present?
      loc_datetime(value)
    else
      EMPTY_VALUE
    end
  end

  def prettify_json(value)
    if value.present?
      parsed_value = JSON.parse(value)
      if FILE_LIST_SCHEMA.(file_list: parsed_value).success?
        render partial: 'orders/file_list', locals: {files: parsed_value}
      else
        value.to_s
      end
    else
      EMPTY_VALUE
    end
  end

  def prettify_boolean(value)
    if value
      '<i class="fas fa-check"></i>'.html_safe
    else
      ''
    end
  end

  def split_data(data, index = 10)
    data = data.presence || {}
    visible = data.keys[0...index]
    hidden = data.keys[index..]
    [data.slice(*visible), data.slice(*hidden)]
  end

  def use_imprint?
    Rails.application.config.app[:use_imprint]
  end

  def expired_class(order)
    if order.estimated_exec_date.nil?
      ''
    elsif order.estimated_exec_date <= Time.now
      'expired'
    elsif order.estimated_exec_date - Rails.application.config.app.fetch(:orders_expiration_warning_days, 1).days <= Time.now
      'about-to-expire'
    else
      ''
    end
  end

  def prepare_order_list(orders)
    orders.map do |order|
      static_fields = {
        code:                {title: order.code, href: order_path(order.code)},
        order_type_code:     order.order_type_name,
        state:               {title: order_state_title(order), icon: order_state_icon(order)},
        created_at:          loc_datetime(order.created_at),
        user:                order.user_full_name,
        ext_code:            order.ext_code,
        archived:            order.archived,
        estimated_exec_date: loc_datetime(order.estimated_exec_date),
        options:             {class: expired_class(order)}
      }

      fields_definition = order.order_type.fields.with_indifferent_access

      custom_fields = order.data.each_with_object({}) do |(key, value), fields|
        fields[key] = format_custom_field(value, fields_definition[key]['type'])
      end

      static_fields.merge(custom_fields)
    end
  end

  def format_custom_field(value, type)
    case type
    when 'datetime' then loc_datetime(value)
    else value
    end
  end
end

app/views/orders/_common_form_fields.html.haml
= f.input(:estimated_exec_date,
          as:    :datetime_picker,
          value: @order.estimated_exec_date,
          label: Order.human_attribute_name(:estimated_exec_date))

app/views/orders/_file_list.html.haml
%ul
  - files.each do |file|
    %li
      = link_to file['origin_name'], file['url']

app/views/orders/_filter_by.html.haml
- custom_fields = custom_fields_for_filter(params[:order_type_id], params[:custom_fields].to_h) if params[:custom_fields]

= form_tag(list_orders_path, method: :get, class: 'form-inline orders-filter') do
  %input(name="filter" value="true" type="hidden")
  .row
    .col-xs-12.col-sm-7.col-md-6.col-lg-7
      .row
        .col-xs-6.col-sm-6.col-md-6.col-lg-4
          %label(for="order_type_id")= t('helpers.enter_order_type')
          = order_type_picker(:order_type_id, value: list_filter.filter_values[:order_type_id])
        .col-xs-6.col-sm-6.col-md-6.col-lg-8
          %label(for="user_id")= t('helpers.enter_user')
          = user_picker(:user_id, value: list_filter.users)
      .row
        .col-xs-6.col-sm-6.col-md-6.col-lg-4
          %label(for="state")= t('helpers.enter_state')
          = order_state_picker(:state, value: list_filter.filter_values[:state])
      .row
        .col-xs-6.col-sm-6.col-md-6.col-lg-4
          %label(for="archived")= t('helpers.enter_archived')
          = order_archived_picker(:archived, value: list_filter.filter_values[:archived])
    .col-xs-12.col-sm-7.col-md-5.col-lg-4.padding-right-0px
      .row
        .col-xs-12.col-sm-12.col-md-12.col-lg-12.no-margin-bottom
          %label= t('helpers.creation_date')
        .col-xs-6.col-sm-12.col-md-12.col-lg-12
          .row
            .col-xs-2.col-sm-2.col-md-2.col-lg-2.margin-top-10px
              %label(for="created_at_from")= t('helpers.from')
            .col-xs-10.col-sm-10.col-md-10.col-lg-10
              = datetime_picker(:created_at_from, value: list_filter.filter_values[:created_at_from])
              %input(name="created_at_from" type="hidden" value="#{list_filter.filter_values[:created_at_from]}")
        .col-xs-6.col-sm-12.col-md-12.col-lg-12
          .row
            .col-xs-2.col-sm-2.col-md-2.col-lg-2.margin-top-10px
              %label(for="created_at_to")= t('helpers.to')
            .col-xs-10.col-sm-10.col-md-10.col-lg-10
              = datetime_picker(:created_at_to, value: list_filter.filter_values[:created_at_to])
              %input(name="created_at_to" type="hidden" value="#{list_filter.filter_values[:created_at_to]}")
      .row
        .col-xs-12.col-sm-12.col-md-12.col-lg-12.no-margin-bottom
          %label= t('helpers.estimated_exec_date')
        .col-xs-6.col-sm-12.col-md-12.col-lg-12
          .row
            .col-xs-2.col-sm-2.col-md-2.col-lg-2.margin-top-10px
              %label(for="estimated_exec_date_from")= t('helpers.from')
            .col-xs-10.col-sm-10.col-md-10.col-lg-10
              = datetime_picker(:estimated_exec_date_from, value: list_filter.filter_values[:estimated_exec_date_from])
              %input(name="estimated_exec_date_from" type="hidden" value="#{list_filter.filter_values[:estimated_exec_date_from]}")
        .col-xs-6.col-sm-12.col-md-12.col-lg-12
          .row
            .col-xs-2.col-sm-2.col-md-2.col-lg-2.margin-top-10px
              %label(for="estimated_exec_date_to")= t('helpers.to')
            .col-xs-10.col-sm-10.col-md-10.col-lg-10
              = datetime_picker(:estimated_exec_date_to, value: list_filter.filter_values[:estimated_exec_date_to])
              %input(name="estimated_exec_date_to" type="hidden" value="#{list_filter.filter_values[:estimated_exec_date_to]}")
    .col-xs-3.col-sm-2.col-md-1.col-lg-1.label-padding-top.label-padding-left-0px
      .row
        .col-xs-6.col-sm-12.col-md-12.col-lg-12
          = submit_tag t('.search'), class: 'btn btn-primary'
        - if use_imprint?
          .col-xs-6.col-sm-12.col-md-12.col-lg-12
            .print-container
              %button(type="submit" name="print" value="#{t('.search')}" class="btn btn-primary")
                = t('.print')

  %hr
  .row
    .col-xs-12.col-sm-12.col-md-6.col-lg-6
      .row
        .col-xs-12.col-sm-12.col-md-12.col-lg-12
          %label(for='custom_field_select')= t('helpers.custom_fields_filter.add')
        .col-xs-10.col-sm-10.col-md-10.col-lg-10
          = order_attribute_picker(:custom_field_select)
        .col-xs-2.col-sm-2.col-md-2.col-lg-2
          %button(type="button" name="add_custom_field_filter" value="#{t('add')}" class="btn btn-primary" disabled)
            = t('add')
  .row#custom-field-filter-container{data: {attributes: custom_fields.to_json}}

:coffee
  $ = jQuery

  $('button[name="print"]').on 'click', (evt) =>
    evt.preventDefault()

    $.ajax '#{print_task_imprint_prints_path}',
      data:
        $('form.orders-filter').serialize()
      method: 'POST'
      complete: (arg) =>
        Application.messenger.show(arg.responseJSON);

  $('.order_type-picker').on 'change', (evt) =>
    clearCustomFieldFilters()
    currentOrderType = $(evt.target).find('option:selected').val()

    if (currentOrderType.length == 0)
      $('.order_attribute-picker').empty().prop('disabled', true).trigger('change')
    else
      Application.setAttributePickerOptions(currentOrderType)

  $('.order_attribute-picker').on 'change', (evt) =>
    currentOrderAttributeType = $(evt.target).find('option:selected').val()
    $('button[name="add_custom_field_filter"]').prop('disabled', !currentOrderAttributeType)

  $('button[name="add_custom_field_filter"]').on 'click', (evt) =>
    currentOrderType = $('.order_type-picker option:selected').val()
    attributeType = $(evt.target).closest('.row').find('.order_attribute-picker option:selected').val()

    if attributeType && $('#' + attributeType).length == 0
      $.ajax '/orders/order_type_attributes/' + currentOrderType,
        method: 'GET'
        success: (data) =>
          renderCustomFieldFilter(attributeType, data.options[attributeType])

  renderCustomFieldFilter = (name, options) =>
    $('#custom-field-filter-container').append(buildCustomFieldFilterInput(name, options))

    labelElement = $('label[for="' + name + '"]')

    if labelElement[0].scrollWidth > labelElement[0].offsetWidth
      new Tooltip(labelElement, { title: options.label })

    if options.type == 'datetime'
      Application.enableDateTimePicker()
      processOnChange('custom_fields['+ name + '][from]')
      processOnChange('custom_fields['+ name + '][to]')

    $('.custom-field-filter-close').on 'click', (evt) =>
      evt.target.closest('.custom-field-filter').remove()

  buildCustomFieldFilterInput = (name, options) =>
    return switch options.type
             when 'string' then buildStringInput(name, options)
             when 'number' then buildNumberInput(name, options)
             when 'boolean' then buildBooleanInput(name, options)
             when 'datetime' then buildDatetimeInput(name, options)
             else null

  buildStringInput = (attributeName, options) =>
    return $('<div>', {class: 'col-xs-12 col-sm-12 col-md-6 col-lg-3 custom-field-filter'}).append(
             $('<div>', {class: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'}).append(
               $('<label>', {for: attributeName, class: 'label-overflow'}).text(options.label),
               $('<i>', class: 'fas fa-times custom-field-filter-close')),
             $('<div>', {class: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'}).append(
               $('<input>', {type: 'text', id: attributeName, name: 'custom_fields[' + attributeName + ']', value: options.value, class: 'form-control'})
             ))

  buildNumberInput = (attributeName, options) =>
    return $('<div>', {class: 'col-xs-12 col-sm-12 col-md-6 col-lg-3 custom-field-filter'}).append(
             $('<div>', {class: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'}).append(
               $('<label>', {for: attributeName, class: 'label-overflow'}).text(options.label),
               $('<i>', class: 'fas fa-times custom-field-filter-close')),
             $('<div>', {class: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'}).append(
               $('<input>', {type: 'number', id: attributeName, name: 'custom_fields[' + attributeName + ']', value: options.value, class: 'form-control'})
             ))

  buildBooleanInput = (attributeName, options) =>
    return $('<div>', {class: 'col-xs-12 col-sm-12 col-md-6 col-lg-3 custom-field-filter'}).append(
             $('<div>', {class: 'col-xs-12 col-sm-12 col-md-12 col-lg-12 ' + attributeName}).append(
               $('<label>', {for: attributeName, class: 'label-overflow label-checkbox'}).text(options.label).append(
                 $('<div>', {class: 'checkbox-margin'}).append(
                   $('<input>', {type: 'hidden', name: 'custom_fields[' + attributeName + ']', value: '0'}),
                   $('<input>', {type: 'checkbox', id: attributeName, name: 'custom_fields[' + attributeName + ']', checked: options.value == '1', value: '1', class: 'custom_boolean'}),
                   $('<span>')
                 )),
                 $('<i>', class: 'fas fa-times custom-field-filter-close')))

  buildDatetimeInput = (attributeName, options) =>
    return $('<div>', {class: 'col-xs-12 col-sm-12 col-md-12 col-lg-6 custom-field-filter custom-field-filter-date'}).append(
             $('<div>', {id: attributeName, class: 'col-xs-12 col-sm-12 col-md-12 col-lg-12'}).append(
               $('<label>', {for: attributeName, class: 'label-overflow'}).text(options.label),
               $('<i>', class: 'fas fa-times custom-field-filter-close')),
             $('<div>', {class: 'col-xs-1 col-sm-1 col-md-1 col-lg-1 margin-top-10px'}).append(
               $('<label>').text(I18n.t('js.from'))),
             $('<div>', {class: 'col-xs-4 col-sm-4 col-md-4 col-lg-4'}).append(
               $('<div>', {class: 'form-group'}).append(
                 $('<div>', {class: 'input-group date datetime-picker'}).data('showclear', true).append(
                   $('<input>', {type: 'text', id: attributeName + '_from', name: 'custom_fields[' + attributeName + '][from]', value: options.value.localized.from if options.value, class: 'form-control'}),
                   $('<span>', {class: 'input-group-addon'}).append(
                     $('<span>', {class: 'fas fa-calendar'})
                   ))),
               $('<input>', {type: 'hidden', name: 'custom_fields[' + attributeName + '][from]', value: options.value.from if options.value, class: 'iso8601'})),
             $('<div>', {class: 'col-xs-1 col-sm-1 col-md-1 col-lg-1 margin-top-10px'}).append(
               $('<label>').text(I18n.t('js.to'))),
             $('<div>', {class: 'col-xs-4 col-sm-4 col-md-4 col-lg-4'}).append(
               $('<div>', {class: 'form-group'}).append(
                 $('<div>', {class: 'input-group date datetime-picker'}).data('showclear', true).append(
                   $('<input>', {type: 'text', id: attributeName + '_to', name: 'custom_fields[' + attributeName + '][to]', value: options.value.localized.to if options.value, class: 'form-control'}),
                   $('<span>', {class: 'input-group-addon'}).append(
                     $('<span>', {class: 'fas fa-calendar'})
                   ))),
               $('<input>', {type: 'hidden', name: 'custom_fields[' + attributeName + '][to]', value: options.value.to if options.value, class: 'iso8601'})))

  renderCustomFieldFilters = () =>
    filters = $('#custom-field-filter-container').data().attributes
    for name, options of filters
      renderCustomFieldFilter(name, options)

  clearCustomFieldFilters = () =>
    $('#custom-field-filter-container').empty()

  processOnChange = (inputName) ->
    $('input[name="' + inputName + '"]').parent().on 'dp.change', (evt) =>
      if evt.date
        value = evt.date.format()
      else
        value = null

      $('input[name="' + inputName + '"]').attr('value', value)

  renderCustomFieldFilters()

  processOnChange('created_at_from')
  processOnChange('created_at_to')
  processOnChange('estimated_exec_date_from')
  processOnChange('estimated_exec_date_to')

  Application.enableOrderTypePicker(true);

app/views/orders/_search_form.html.haml
.row
  .col-xs-12
    .orders-filter-container(role="tabpanel")
      %ul.nav.nav-tabs(role="tablist")
        %li.active(role="presentation")
          %a(role="tab" aria-controls="filter" href="#filter" data-toggle="tab")
            = t('.filter_records')
        %li(role="presentation")
          %a(role="tab" aria-controls="search" href="#search" data-toggle="tab")
            = t('.search_for_record')
      .tab-content
        #search.tab-pane(role="tabpanel")
          .row
            .col-xs-12.col-sm-12.col-md-12.col-lg-12
              .col-xs-6.col-sm-6.col-md-4.col-lg-4
                = render partial: 'search_by', locals: { field: :code, field_value: '', path: search_order_by_path(:code) }
              .col-xs-6.col-sm-6.col-md-4.col-lg-4
                = render partial: 'search_by', locals: { field: :ext_code, field_value: '', path: search_order_by_path(:ext_code) }
        #filter.tab-pane.active(role="tabpanel")
          .row
            .col-xs-12.col-sm-12.col-md-12.col-lg-12
              = render partial: 'filter_by'

app/views/orders/index.html.haml
- content_for(:title, t('.title'))
%h2= t('.title')
= render partial: 'search_form'

.row
  .col-xs-12
    - if orders.present?
      .total-items
        = "#{t('orders.total_items')} #{total_items}"
      .table-responsive.table-nowrap.overflow-visible.orders-list
        #order-list-container
      - with_custom_profile = list_filter.filter_values[:order_type_id].present?
      - options = {profile: with_custom_profile ? custom_profile(orders.first.order_type) : common_profile,
                    withCustomProfile: with_custom_profile,
                    filterParams: params,
                    pageSize: 25}
      :javascript
        Application.renderOrderList(document.getElementById('order-list-container'),
                                    JSON.parse('#{options.to_json.html_safe}'))
    - else
      %h4.empty-list= t('.no_orders_found')
= link_to t('add'), new_order_path, class: 'btn btn-primary'

app/views/orders/list.json.erb
<%= raw(prepare_order_list(orders).to_json) %>

app/views/orders/new.html.haml
- content_for(:title, t('.title'))
.authform.new_order
  = render partial: 'new_form'

app/views/orders/show.html.haml
- title = "#{@order.code} #{@order.order_type_name}"
- content_for(:title, title)
- @hbw_options = { entity_code: @order.code, entity_type: @order.order_type_code, entity_class: 'order', widgetContainer: '#hbw-bp-control-buttons-container', task_id: params[:task_id] }
%h2
  = title
.row
  .col-xs-12
    #hbw-bp-control-buttons-container.hbw-body
    .panel.panel-default
      .panel-heading
        %h4.panel-title.collapsable
          %a(data-toggle='collapse' data-target='#order_data' hrev='#')
            = t('.order_data')
          .btn-group.order_data_group.pull-right
            = link_to('', edit_order_path(@order.code), class: 'fas fa-pencil-alt pull-right', title: t('.edit_title'))
            - if use_imprint?
              .dropdown.print-dropdown.pull-right
                - if @order.order_type_print_form_code.present?
                  %a.fas.fa-print.dropdown-toggle.pull-right(data-toggle='dropdown' title="#{t('.print_title')}")
                  %ul.dropdown-menu
                    %li
                      = link_to(t('orders.print'), print_imprint_prints_path(order_code: @order.code, convert_to_pdf: false))
                    %li
                      = link_to(t('orders.print_pdf'), print_imprint_prints_path(order_code: @order.code, convert_to_pdf: true))
                - else
                  %a.fas.fa-print.dropdown-toggle.pull-right.disabled(data-toggle='dropdown' title="#{t('.empty_code_title')}")
        .clearfix
      .panel-body.collapse.in#order-data
        = render partial: 'data', locals: { data: @order.data }