config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions'
  }

  get '/sign_in_by_token/:token' => 'sessions#sign_in_by_token'

  devise_scope :user do
    get  '/redirect_to_keycloak', to: 'sessions#redirect_to_keycloak'
    get  '/authenticate_by_keycloak', to: 'sessions#authenticate_by_keycloak'
  end

  root to: 'orders#index'

  resources :users do
    post :add, on: :collection
    get :lookup, on: :collection
    put :generate_api_token, on: :member
    delete :clear_api_token, on: :member
  end

  get '/orders/search_by/:field',
      to:          'orders#search_by',
      as:          :search_order_by,
      constraints: {field: /code|ext_code/}

  get '/orders/order_type_attributes/:id' => 'orders#get_order_type_attributes'

  get '/orders/list', to: 'orders#list'

  get '/tasks', to: 'tasks#index'

  resources :orders, only: [:show, :edit, :update, :index, :new, :create]

  resources :profiles, only: [:create, :update]

  namespace :imprint do
    resources :prints, only: [] do
      get :print, on: :collection
      post :print_task, on: :collection
    end
  end

  namespace :admin do
    resources :order_types, only: [:index, :show, :create, :destroy] do
      get :lookup, on: :collection
      put :activate, on: :member
      delete :dismiss, on: :member
    end
  end

  namespace :api, defaults: {format: :json} do
    scope module:      :v1,
          constraints: APIConstraints.new(version: 1, default: true) do
      actions = [:index, :show, :create, :update, :destroy]

      resources :users, only: actions, constraints: {id: /.*/}
      resources :orders, only: actions
      resources :profiles, only: actions
    end
  end

  mount HBW::Engine => '/widget', as: :hbw
end

app/views/layouts/_form_errors.html.haml
- if record.errors.any?
  #error_explanation.alert.alert-danger
    .alert.alert-danger
      = t('.errors', count: record.errors.count)
    %ul
      - record.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle(data-target=".navbar-collapse" data-toggle="collapse" type="button")
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse
      %ul.nav.navbar-nav
        %li.logo
          = link_to list_orders_url  do
            = t('logo')
            %img{src: asset_bundle_path("logo.svg")}
        - if user_signed_in?
          %li
            = link_to orders_path do
              %span.fas.fa-list
              = t('.orders')
          - if current_user.admin?
            %li
              = link_to admin_order_types_path do
                %span.fas.fa-cog
                = t('.setup_order_types')
            %li
              = link_to users_path do
                %span.fas.fa-users
                = t('.users')
          %li
            = link_to tasks_path do
              %span.fas.fa-tasks
              = t('.tasks')
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            = link_to('#', class: 'dropdown-toggle', role: :button, 'data-toggle' => 'dropdown') do
              %span.fas.fa-user
              = current_user.name
              %span.caret
            %ul.dropdown-menu{role: :menu}
              - link_to_manual = Rails.application.config.app.fetch(:link_to_manual, '')
              - if link_to_manual.present?
                %li
                  %a(href="#{link_to_manual}")
                    %span.fas.fa-question-circle
                    = t('.help')
              - if current_user.admin?
                %li
                  %a(href="#{Apitome.configuration.mount_at}")
                    %span.fas.fa-info-circle
                    = t('.rest_api')
              %li
                = link_to destroy_user_session_path, :method=>'delete' do
                  %span.fas.fa-sign-out-alt
                  = t('.sign_out')

          %li#hbw-tasks-list-button

app/views/layouts/application.html.haml
!!!
%html.hbw-styles
  %head
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : 'Homs'
    %meta{ name: 'description', content: "#{content_for?(:description) ? yield(:description) : 'Homs'}"}
    = stylesheet_bundle_tag 'hbw'
    = stylesheet_bundle_tag 'application'
    = javascript_bundle_tag 'hbw'
    %link{href: '/assets/css/fontawesome.min.css', rel: 'stylesheet'}
    = javascript_bundle_tag 'application'
    = csrf_meta_tags
  %body
    :coffee
      I18n.locale = '#{I18n.locale}'
    %header
      = render 'layouts/navigation'
      = Rails.application.config.app.fetch(:announcement, '').to_s.html_safe

    %main.container(role="main")
      .container= yield

    :coffee
      Application.messenger.show(#{flash_messages.to_json.html_safe});
    - if hbw_available?
      #hbw-tasks
      :coffee
        window.HBWidget = new (window.HBW)(#{hbw_options.to_json.html_safe})